# Generated by Django 5.2.1 on 2025-05-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='experience',
            field=models.CharField(default='Beginner', max_length=100),
        ),
    ]
