# Generated by Django 5.2.1 on 2025-05-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_caretaker_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretaker',
            old_name='city',
            new_name='citys',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='email',
            new_name='emails',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='experience',
            new_name='experiences',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='full_name',
            new_name='full_names',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='password',
            new_name='passwords',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='phone_number',
            new_name='phone_numbers',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='specialization',
            new_name='specializations',
        ),
    ]
