# Generated by Django 5.2.1 on 2025-05-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_caretaker_user_patient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
