# Generated by Django 5.2.1 on 2025-05-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_caretaker_availability_caretaker_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
