# Generated by Django 5.2.1 on 2025-05-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_caretaker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='image',
            field=models.ImageField(upload_to='caretaker_images/'),
        ),
    ]
