# Generated by Django 5.2.1 on 2025-05-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Description',
            field=models.CharField(default='No description', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='requested_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
