# Generated by Django 5.2.1 on 2025-05-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0009_booking_description_booking_book_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
