# Generated by Django 5.2.1 on 2025-06-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0011_alter_booking_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretaker',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='citys',
            new_name='locations',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='specializations',
            new_name='role',
        ),
    ]
