# Generated by Django 5.2.1 on 2025-06-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0012_rename_image_caretaker_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
